/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2;

import edu.upb.chatupb_v2.bl.server.ChatService;
import edu.upb.chatupb_v2.bl.server.Controller;
import edu.upb.chatupb_v2.bl.server.IChatView;
import edu.upb.chatupb_v2.bl.server.SocketClient;
import edu.upb.chatupb_v2.repository.comands.*;
import lombok.Getter;

import javax.swing.*;
import java.io.IOException;
import java.util.*;

/**
 *
 * @author USER 1
 */
public class JUi extends javax.swing.JFrame implements IChatView {
    //YA NO HAY CHAT SERVER!
//    ChatServer server;
    private ChatService chatService;
//    SocketClient socketClient;
    private final String username = "Santiago";
    private final UUID userId = UUID.randomUUID();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JUi.class.getName());

    /**
     * Creates new form JUi
     */
    public JUi() {
        initComponents();
        this.chatService = new ChatService(this, username, userId.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        // Labels
        JLabel jLabelIP = new JLabel("Dirección IP:");
        JLabel jLabelUser = new JLabel("Nombre de Usuario:");

        // Campos
        jIP = new javax.swing.JTextField();
        JTextField jTextUserName = new JTextField();
        jTextMensaje = new javax.swing.JTextField();

        // Botones
        JButton jbConectar = new JButton("Conectar");
        JButton jbEnviar = new JButton("Enviar");
        JButton jBforBuzzing = new JButton("Buzz");
        JButton jBOffline = new JButton("Fuera de Linea");

        // Estado
        jOnline = new javax.swing.JLabel("Status: Offline");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);


        jbConectar.addActionListener(evt -> chatService.connect(jIP.getText()));
        jbEnviar.addActionListener(evt -> chatService.sendMessage(jTextMensaje.getText()));
        jBforBuzzing.addActionListener(evt -> chatService.sendBuzz());
        jBOffline.addActionListener(evt -> chatService.sendBye());

        pack();
        setLocationRelativeTo(null);

        // ------------------ HORIZONTAL ------------------
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                        // Fila IP y Usuario
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelIP)
                                        .addComponent(jIP, 120, 120, 120))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelUser)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextUserName, 120, 120, 120)
                                                .addComponent(jbConectar)
                                                .addComponent(jBforBuzzing)))
                                                .addComponent(jBOffline)
                        )

                        // Estado
                        .addComponent(jOnline)

                        // Fila mensaje
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextMensaje, 260, 260, Short.MAX_VALUE)
                                .addComponent(jbEnviar)
                        )
        );

        // ------------------ VERTICAL ------------------
        layout.setVerticalGroup(
                layout.createSequentialGroup()

                        // Labels
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelIP)
                                .addComponent(jLabelUser)
                        )

                        // Campos + botones
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jIP)
                                .addComponent(jTextUserName)
                                .addComponent(jbConectar)
                                .addComponent(jBforBuzzing)
                        )
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBOffline)
                        )
                        // Estado
                        .addComponent(jOnline)

                        .addGap(40)

                        // Mensaje
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextMensaje)
                                .addComponent(jbEnviar)
                        )
        );

        // Listeners
//        jbConectar.addActionListener(this::jbConectarActionPerformed);
//        jbEnviar.addActionListener(this::jbEnviarActionPerformed);
//        jBforBuzzing.addActionListener(this::jBforBuzzingActionPerformed);

        pack();
        setLocationRelativeTo(null); // Centra la ventana
    }


    public void init() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> this.setVisible(true));
    }

    private javax.swing.JTextField jIP;
    private javax.swing.JLabel jOnline;
    private javax.swing.JTextField jTextMensaje;



    @Override
    public void updateStatus(String status) {
        jOnline.setText(status);
    }

    @Override
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Información", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void showError(String error) {
        JOptionPane.showMessageDialog(this, error, "Error", JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public boolean showInvitationDialog(String userName, String id) {
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Invitación recibida de: " + userName + " (ID: " + id + "). ¿Aceptar?",
                "Nueva Conexión Entrante",
                JOptionPane.YES_NO_OPTION);
        return respuesta == JOptionPane.YES_OPTION;
    }

    @Override
    public void showBuzzNotification(String senderName) {
        JOptionPane.showMessageDialog(null, senderName + " Te ha enviado un zumbido", "Zumbido", JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void showByeNotification (String id){
        JOptionPane.showMessageDialog(null, id + " Se ha desconectado", "Disconnected", JOptionPane.INFORMATION_MESSAGE);

    }
}
