/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2;

import edu.upb.chatupb_v2.bl.server.ChatServer;
import edu.upb.chatupb_v2.bl.server.Controller;
import edu.upb.chatupb_v2.bl.server.SocketClient;
import edu.upb.chatupb_v2.repository.comands.*;
import lombok.Getter;

import javax.swing.*;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ConnectException;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Time;
import java.util.*;

/**
 *
 * @author USER 1
 */
public class JUi extends javax.swing.JFrame {
    //YA NO HAY CHAT SERVER!
//    ChatServer server;
    SocketClient socketClient;
    private String username = "Santiago";
    private UUID userId = UUID.randomUUID();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JUi.class.getName());

    /**
     * Creates new form JUi
     */
    public JUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // Labels
        jLabelIP = new javax.swing.JLabel("Dirección IP:");
        jLabelUser = new javax.swing.JLabel("Nombre de Usuario:");

        // Campos
        jIP = new javax.swing.JTextField();
        jTextUserName = new javax.swing.JTextField();
        jTextMensaje = new javax.swing.JTextField();

        // Botones
        jbConectar = new javax.swing.JButton("Conectar");
        jbEnviar = new javax.swing.JButton("Enviar");
        jBforBuzzing = new javax.swing.JButton("Buzz");

        // Estado
        jOnline = new javax.swing.JLabel("Status: Offline");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);

        // ------------------ HORIZONTAL ------------------
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                        // Fila IP y Usuario
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelIP)
                                        .addComponent(jIP, 120, 120, 120))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelUser)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextUserName, 120, 120, 120)
                                                .addComponent(jbConectar)
                                                .addComponent(jBforBuzzing)))
                        )

                        // Estado
                        .addComponent(jOnline)

                        // Fila mensaje
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextMensaje, 260, 260, Short.MAX_VALUE)
                                .addComponent(jbEnviar)
                        )
        );

        // ------------------ VERTICAL ------------------
        layout.setVerticalGroup(
                layout.createSequentialGroup()

                        // Labels
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelIP)
                                .addComponent(jLabelUser)
                        )

                        // Campos + botones
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jIP)
                                .addComponent(jTextUserName)
                                .addComponent(jbConectar)
                                .addComponent(jBforBuzzing)
                        )

                        // Estado
                        .addComponent(jOnline)

                        .addGap(40)

                        // Mensaje
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextMensaje)
                                .addComponent(jbEnviar)
                        )
        );

        // Listeners
        jbConectar.addActionListener(evt -> jbConectarActionPerformed(evt));
        jbEnviar.addActionListener(evt -> jbEnviarActionPerformed(evt));
        jBforBuzzing.addActionListener(evt -> jBforBuzzingActionPerformed(evt));

        pack();
        setLocationRelativeTo(null); // Centra la ventana
    }

    private void jIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIPActionPerformed

    private void jTextMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMensajeActionPerformed

    private void jTextUserActionPerformed(java.awt.event.ActionEvent evt){

    }

    private void jBforBuzzingActionPerformed(java.awt.event.ActionEvent evt){
        for (SocketClient sc : Controller.getClients()){
            Buzzing bz = new Buzzing(this.userId.toString());
            try {
                sc.send(bz.createFormat());
            } catch (IOException e){
                e.printStackTrace();
            }
        }
    }
    // Define el listener como un campo de la clase
    @Getter
    private SocketClient.SocketListener connectionListener = new SocketClient.SocketListener() {
        @Override
        public void onInvitationReceived(Invitation invitation) {

            SwingUtilities.invokeLater(() -> {
                int respuesta = javax.swing.JOptionPane.showConfirmDialog(JUi.this,
                        "Invitación recibida de: " + invitation.getUserName() +
                                " (ID: " + invitation.getIdUser() + "). ¿Aceptar?",
                        "Nueva Conexión Entrante",
                        javax.swing.JOptionPane.YES_NO_OPTION);

                if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                    Accept acp = new Accept(userId.toString(), username);
                    try {
                        for (SocketClient sc: Controller.getClients()){
                            if (sc.getUID().equals(invitation.getIdUser())){
                                sc.send(acp.createFormat());
                            }
                        }
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                } else {
                    Decline dec = new Decline();
                    try {
                        socketClient.send(dec.createFormat());
                    } catch (IOException e) {
                        throw new RuntimeException(e);
                    }
                }
            });
        }

        @Override
        public void onAcceptReceived(Accept accept){
            jOnline.setText("Status: Online");
            JOptionPane.showMessageDialog(null, "Aceptado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
        }

        @Override
        public void onDeclineReceived(Decline decline) {
            jOnline.setText("Status: Rejected");
            JOptionPane.showMessageDialog(null, "Rechazado", "Resultado", JOptionPane.INFORMATION_MESSAGE);
            socketClient.close();
        }

        @Override
        public void onHelloReceived(Hello hello) {

        }

        @Override
        public void onAcceptHelloReceived(AcceptHello acceptHello) {

        }

        @Override
        public void onDeclineHelloReceived(DeclineHello declineHello) {

        }

        @Override
        public void onChatReceived(Chat chat) {
            System.out.println("ID Mensaje: " + chat.getIdMessage());
            System.out.println("Mensaje: " + chat.getMessage());
        }

        @Override
        public void onConfirmedReceived(ConfirmRecived confirmRecived) {

        }

        @Override
        public void onDeleteMessageReceived(DeleteMessage deleteMessage) {

        }

        @Override
        public void onBuzzingReceived(Buzzing buzzing) {
            String name = " ";
            for (SocketClient sc:Controller.getClients()){
                if (sc.getUID().equals(buzzing.getIdUser())){
                    name = sc.getNombre();
                }
            }
            JOptionPane.showMessageDialog(null, name + " Te ha enviado un zumbido", "Zumbido", JOptionPane.INFORMATION_MESSAGE);
        }

        @Override
        public void onPinMessageReceived(PinMessage pinMessage) {

        }

        @Override
        public void onUniqueMessageReceived(UniqueMessage uniqueMessage) {

        }

        @Override
        public void onThemeReceived(Theme theme) {

        }
    };
    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {
        String ip = jIP.getText();

            new Thread(() -> {
                try {
                    // 1. Crear la conexión saliente
                    socketClient = new SocketClient(ip);
                    // 2. Asignar EL MISMO listener que usa el servidor
                    socketClient.setListener(username, userId, connectionListener);
                    Controller.addClients(socketClient);
                    // 3. Iniciar escucha
                    socketClient.start();

                    // 4. Enviar invitación
                    Invitation myInvite = new Invitation(userId.toString(), username);
                    socketClient.send(myInvite.createFormat());

                    SwingUtilities.invokeLater(() -> jOnline.setText("Status: Enviando invitación..."));

                } catch (Exception e) {
                    SwingUtilities.invokeLater(() ->
                            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage())
                    );
                }
            }).start();

//        if (server != null) {
//            new Thread(() -> {
//                while (true) {
//                    try {
//                        server.enviarHello();
//                        Thread.sleep(100);
//                    } catch (InterruptedException e) {
//                        throw new RuntimeException(e);
//                    }
//                }
//            }).start();
//        }
    }//GEN-LAST:event_jbConectarActionPerformed

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Chat chat = new Chat(this.userId.toString(), UUID.randomUUID().toString(), jTextMensaje.getText());
            for (SocketClient sc : Controller.getClients()){
                sc.send(chat.createFormat());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
//    }//GEN-LAST:event_jbEnviarActionPerformed

    /**
     */
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            this.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jIP;
    private javax.swing.JLabel jOnline;
    private javax.swing.JLabel jLabelIP;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JTextField jTextMensaje;
    private javax.swing.JTextField jTextUserName;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JButton jBforBuzzing;
    // End of variables declaration//GEN-END:variables
}
